### ISSUE TITLE
(Error/Bug) MaxListenersExceededWarning

### ISSUE THREAD

**Issue by idontreallywolf** [idontreallywolf/project_pleb#45]
(node:22976) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 
11 error listeners added. 
Use emitter.setMaxListene rs() to increase limit

**Comment by Toddez** [comment]
Will look into this

**Comment by Toddez** [comment]
> Will look into this

Cannot replicate the issue but added a small (potential) fix in maxlisteners branch
Could you see if this fixes the issue?

**Comment by idontreallywolf** [comment]
> > Will look into this
> 
> Cannot replicate the issue but added a small (potential) fix in maxlisteners branch
> Could you see if this fixes the issue?

Could not replicate it either.
